matrix:
  include:
      - language: julia
        julia: 0.7
        os: linux
        dist: trusty
        sudo: required
      - language: julia
        julia: 1.0
        os: linux
        dist: trusty
        sudo: required
      - language: julia
        julia: nightly
        os: linux
        dist: trusty
        sudo: required

      - language: julia
        julia: 0.7
        os: osx
      - language: julia
        julia: 1.0
        os: osx
      - language: julia
        julia: nightly
        os: osx

notifications:
    email: false
  script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
    - $TESTCMD -e 'using Pkg; Pkg.clone(pwd());
          Pkg.build("GtkSourceWidget");
          Pkg.test("GtkSourceWidget"; coverage=true)'
after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("GtkSourceWidget")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'