language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0

notifications:
    email: false
after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("GtkSourceWidget")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'