language: julia
sudo: required
os:
  - linux
  - osx
  - windows
julia:
  - 1.3
  - nightly
matrix:
  allow_failures:
  - julia: nightly
notifications:
  email: false
addons:
  apt:
    packages:
      - xvfb
      - xauth
coveralls: true

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
  - $TESTCMD -e 'using Pkg; Pkg.build(verbose=true); Pkg.test(coverage=true)'
