matrix:
  include:
      - language: julia
        julia: 0.7
        os: linux
        dist: trusty
        sudo: required
      - language: julia
        julia: 1.0
        os: linux
        dist: trusty
        sudo: required
      - language: julia
        julia: nightly
        os: linux
        dist: trusty
        sudo: required

      - language: julia
        julia: 0.7
        os: osx
      - language: julia
        julia: 1.0
        os: osx
      - language: julia
        julia: nightly
        os: osx

notifications:
    email: false
after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("GtkSourceWidget")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'